spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.113/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

server:
  context-path: /sell


#日志配置方式一，一般在项目中使用方式二
#%d:表示日期   %msg：表示信息   %n：换行
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/      #会多一个spring.log日志文件 默认
#  file: /var/log/tomcat/sell.log   #这样就会把日志输出到sell.log中
#  level: debug